function buat_login(){
	var elem = document.getElementById('x');
	elem.parentElement.removeChild(elem);
	var p = document.createElement('p');
	p.className='tulisan_login';
	p.innerHTML = 'SILAHKAN MENDAFTAR';
	var element = document.getElementsByTagName('div')[0];
	element.appendChild(p);
	var form = document.createElement('form');
	element.appendChild(form);
	var label_nama_user = document.createElement('label');
	label_nama_user.innerHTML = 'Nama User';
	form.appendChild(label_nama_user);
	var nama_user = document.createElement('input');
	nama_user.type='text';
	nama_user.name='nama user';
	nama_user.placeholder='Nama User';
	nama_user.className='form_login';
	form.appendChild(nama_user);
	var label_nomor_handphone = document.createElement('label');
	label_nomor_handphone.innerHTML = 'Nomor Handphone';
	form.appendChild(label_nomor_handphone);
	var nomor_handphone = document.createElement('input');
	nomor_handphone.type='number';
	nomor_handphone.name='nomor handphone';
	nomor_handphone.placeholder='Nomor Handphone';
	nomor_handphone.className='form_login';
	form.appendChild(nomor_handphone);
	var label_username = document.createElement('label');
	label_username.innerHTML = 'Username';
	form.appendChild(label_username);
	var username = document.createElement('input');
	username.type='text';
	username.name='username';
	username.placeholder="Username atau email";
	username.className='form_login';
	form.appendChild(username);
	var label_password = document.createElement('label');
	label_password.innerHTML='Password';
	form.appendChild(label_password);
	var password = document.createElement('input');
	password.type='password';
	password.name='password';
	password.placeholder='Password';
	password.className='form_login';
	form.appendChild(password);
	var tombol=document.createElement('input');
	tombol.type='submit';
	tombol.value='DAFTAR SEKARANG';
	tombol.className='tombol_login';
	form.appendChild(tombol);
}
